### ISSUE TITLE
Start does not work

### ISSUE THREAD

**Issue by l1x** [jihchi/reason-react-realworld-example-app#17]
Doing this:

```
git clone https://github.com/jihchi/rescript-react-realworld-example-app.git
cd rescript-react-realworld-example-app
npm install
npm start
```

Results in this:

```
▼ @jihchi/plugin-rescript

  Dependency on @rescript/react
  Dependency on @ryyppy/rescript-promise
  Dependency on bs-fetch
  Dependency on bs-webapi
  Dependency Finished
  >>>> Start compiling
  >>>> Finish compiling
[snowpack] (node:10862) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/app/rescript-react-realworld-example-app/node_modules/@rescript/react/lib/bs/src/legacy/ReactDOMRe.cmi'
    at FSWatcher.start (internal/fs/watchers.js:210:26)
    at Object.watch (fs.js:1444:11)
    at createFsWatchInstance (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109769:17)
    at setFsWatchListener (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109816:15)
    at NodeFsHandler._watchWithNodeFs (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109977:14)
    at NodeFsHandler._handleFile (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:110041:23)
    at NodeFsHandler._addToNodeFs (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:110274:21)
[snowpack] (node:10862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 331)
[snowpack] (node:10862) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/app/rescript-react-realworld-example-app/node_modules/@rescript/react/lib/bs/src/legacy/ReasonReact.cmt'
    at FSWatcher.start (internal/fs/watchers.js:210:26)
    at Object.watch (fs.js:1444:11)
    at createFsWatchInstance (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109769:17)
    at setFsWatchListener (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109816:15)
    at NodeFsHandler._watchWithNodeFs (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109977:14)
    at NodeFsHandler._handleFile (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:110041:23)
    at NodeFsHandler._addToNodeFs (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:110274:21)
[snowpack] (node:10862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 332)
[snowpack] (node:10862) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/app/rescript-react-realworld-example-app/node_modules/@rescript/react/lib/bs/src/legacy/ReasonReact.d'
    at FSWatcher.start (internal/fs/watchers.js:210:26)
    at Object.watch (fs.js:1444:11)
    at createFsWatchInstance (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109769:17)
    at setFsWatchListener (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109816:15)
    at NodeFsHandler._watchWithNodeFs (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:109977:14)
    at NodeFsHandler._handleFile (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:110041:23)
    at NodeFsHandler._addToNodeFs (/home/app/rescript-react-realworld-example-app/node_modules/snowpack/lib/index.js:110274:21)
[snowpack] (node:10862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 333)
```

I have tried with Yarn and Npm. Same results.

**Comment by jihchi** [comment]
I noticed the error message from the provided logs:

```
...Error: ENOSPC: System limit for number of file watchers reached, watch ...
```

Maybe try to lift your system's file watcher limit? for example: 

> If you are using Linux, your project is hitting your system's file watchers limit
> 
> To fix this, on your terminal, try:
> 
> ```sh
> echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
> ```

(source from [stackoverflow](https://stackoverflow.com/a/55543310/5392257))

**Comment by deogemini** [comment]
thanks @jihchi your solution was great help to me
